substitutions:
  DEVICENAME: "bt_bridge"
  DEVICE_NAME: "bt_bridge"

<<: !include "common/esp-wrover-kit.yaml"
<<: !include "common/Restart.yaml"

# Enable logging
logger:
#   Helps with bt scan
#  level: VERY_VERBOSE

# Enable Home Assistant API
api:
  password: !secret bt_bridge_ota

ota:
  password: !secret bt_bridge_ota
  
binary_sensor:
  - platform: gpio
    pin:
      number: 4
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Dryer Relay"
    filters:
      - delayed_on_off: 5s
                
#Reboot the bluetooth bridge @ 3:30am      
time:
  - platform: homeassistant
    on_time:
      - seconds: 0
        minutes: 30
        hours: 3
        days_of_week: MON-SUN
        then:
           - button.press: restart_${DEVICE_NAME}