esphome:
  name: bt_bridge
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:
#   Helps with bt scan
#  level: VERY_VERBOSE

# Enable Home Assistant API
api:
  password: !secret bt_bridge_ota

ota:
  password: !secret bt_bridge_ota

# Enable Bluetooth scanning for this ESP32
esp32_ble_tracker:

bluetooth_proxy:
  active: true
  
binary_sensor:
  - platform: gpio
    pin:
      number: 4
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Dryer Relay"
    filters:
      - delayed_on_off: 5s
                
sensor:
  - platform: wifi_signal
    name: "BT_Bridge WiFi Signal"
    update_interval: 60s

#Reboot the bluetooth bridge @ 3:30am      
time:
  - platform: homeassistant
    on_time:
      - seconds: 0
        minutes: 30
        hours: 3
        days_of_week: MON-SUN
        then:
           - button.press: restart1
button:
  - platform: restart
    name: "bt_bridge Restart"
    id: restart1