esphome:
  name: depth-sensor
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "eaf85eb2e25747d973789e7d35ab8b81"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80
  
status_led:
  pin:
    number: D4
    inverted: true
  
sensor:
  - platform: ultrasonic
    trigger_pin: D2
    echo_pin: D1
    name: "Ultrasonic Sensor"
    update_interval: 500ms
    accuracy_decimals: 3
    filters:
        - delta: 0.002
        - lambda: return 0.360 - x;