substitutions:
  DEVICENAME: "depth-sensor"

<<: !include "common/d1-mini.yaml"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "eaf85eb2e25747d973789e7d35ab8b81"
  
sensor:
  - platform: ultrasonic
    trigger_pin: D2
    echo_pin: D1
    name: "Ultrasonic Sensor"
    update_interval: 500ms
    accuracy_decimals: 3
    filters:
        - delta: 0.002
        - lambda: return 0.360 - x;