# Fed by the 12V buck converter in rack 1, lan by distribution switch 4 (1.6.3.6)
# Monitors main 24V PSU and its batteries.

substitutions:
  DEVICENAME: "esp32-eth-0"
  DEVICE_NAME: "esp32_eth_0"

<<: !include "common/LilyGO-T-ETH-POE.yaml"
<<: !include "common/Restart.yaml"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80