#https://randomnerdtutorials.com/esp32-pinout-reference-gpios/

esphome:
  name: ${DEVICENAME}

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

esp32_ble_tracker:

bluetooth_proxy:
  active: true
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
sensor:
  - platform: wifi_signal
    name: "${DEVICENAME} WiFi Signal"
    update_interval: 60s